# ASSIGNMENT 2

#### Question 1

In [20]:
import numpy as np

a = np.array([1, 7, 3, 10, 14, 76,4])
indices = []

for p in a:
    for q in a:
        if p == q:
            pass
        else:
            if (p+q) % 7 == 0:
                for i in range(7):  # to append indices rather than numbers
                    if a[i] == p:
                        element1 = i
                    if a[i] == q:
                        element2 = i
                indices.append([element1,element2])

new_length = int(len(indices)/2) #reduces values that occur twice
new_indices = []
for k in range(new_length):
    new_indices.append(indices[k])
print(new_indices)


[[0, 5], [1, 4], [2, 6], [3, 6]]


# 

#### Question 2

In [21]:
import numpy as np
A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])
B = np.array([[5, 6, 7],[7, 8, 9],[1, 2, 3]])

A_inv = np.linalg.inv(A)
Dot_with_B = np.dot(A_inv,B)
element_wise_multiplication = A_inv * B

print("Inverse:")
print(A_inv)
print("\n"*1)
print("Dot Product")
print(Dot_with_B)
print("\n"*1)
print("Element wise Multiplication")
print(element_wise_multiplication)

Inverse:
[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]


Dot Product
[[ 0.86046512  1.1627907   1.46511628]
 [ 2.06976744  2.41860465  2.76744186]
 [-0.55813953 -0.68217054 -0.80620155]]


Element wise Multiplication
[[ 1.74418605 -0.8372093   0.65116279]
 [ 2.27906977  0.55813953 -0.41860465]
 [-0.27131783  0.21705426  0.11627907]]


# 

#### Question 3

In [22]:
import numpy as np
import pandas as pd

data = np.array([[1, 2, 3, 4, 5], [1, 8, 2, 10, 11], [4, 5, 6, 7, 8],
[7, 8, 9, 10, 11], [7, 18, 19, 10, 11]])

df = pd.DataFrame(data, columns = ['A','B','C','D','E'])
print("df:")
print(df)
print("\n"*2)

df2 = df.sort_values(by="C")

print("First Two Rows:")
print(df2.head(2))
print("\n"*1)

print("Last Two Rows:")
print(df2.tail(2))
print("\n"*1)

print("df2 Values as a Numpy array:")
print(np.array(df2))

df:
   A   B   C   D   E
0  1   2   3   4   5
1  1   8   2  10  11
2  4   5   6   7   8
3  7   8   9  10  11
4  7  18  19  10  11



First Two Rows:
   A  B  C   D   E
1  1  8  2  10  11
0  1  2  3   4   5


Last Two Rows:
   A   B   C   D   E
3  7   8   9  10  11
4  7  18  19  10  11


df2 Values as a Numpy array:
[[ 1  8  2 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 7 18 19 10 11]]


# 

#### Question 4

In [23]:
import numpy as np
from numpy.ma.core import absolute

A = np.array([[1, 2, 0],[0, 5, 6],[7, 0, 9]])

eigenvalues, eigenvectors  = np.linalg.eig(A)
print("Eigen Values are:")
print(eigenvalues)

absolute_value = []
for k in eigenvalues:
    i = abs(k)
    absolute_value.append(i)
spectral_radius = max(absolute_value)
print("\n"*1)
print("Spectral Radius:")
print(spectral_radius)

Eigen Values are:
[10.5740355 +0.j          2.21298225+2.70229602j  2.21298225-2.70229602j]


Spectral Radius:
10.57403549813147


# 

#### Question 5

In [24]:
import numpy as np
B = np.array([[5, 6, 7],[7, 8, 9],[1, 2, 3]])

U, S, Vt = np.linalg.svd(B, full_matrices=False)
Sigma = np.diag(S) #Diagonalising 1D array S.

B_recon = U @ Sigma @ Vt

accuracy = np.allclose(B, B_recon, atol=1e-10)
print(f"Boolean Result: {accuracy}")
print("\n"*1)

K2_B= (max(S)/min(S))
print(f"Spectral (2-norm) condition number: {K2_B}")

Boolean Result: True


Spectral (2-norm) condition number: 1.2095847478372948e+16
